---
abstract: 'Interface to the CommonMarkGFM C library'
author:
  - 'Nick Wellnhofer <wellnhofer@aevum.de>'
build_requires:
  Encode: '0'
  Test::More: '0'
configure_requires:
  Alien::Base::Wrapper: '1.02'
  Alien::Libcmark_gfm: '0'
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CommonMarkGFM
requires:
  perl: '5.010'
resources:
  bugtracker: https://github.com/nwellnhof/perl-commonmark/issues
  repository: https://github.com/nwellnhof/perl-commonmark.git
version: '0.280301'
x_serialization_backend: 'YAML::Tiny version 1.70'
